json.extract! review, :id, :accuracy_rating,
  :communication_rating,
  :cleanliness_rating,
  :location_rating,
  :checkin_rating,
  :value_rating,
  :description,
  :review_helpfulness,
  :author_id,
  :listing_id,
  :created_at
